# Generated by Django 5.1.2 on 2024-11-13 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("credit_bureau", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="correct_answer",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
