# Generated by Django 5.1.2 on 2024-11-13 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("credit_bureau", "0002_question_correct_answer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="correct_answer",
        ),
    ]
